service:
  name: auth-service

discovery:
  backend:
    host: localhost
    port: 6379
    key: discovery-records

server:
  host: localhost
  port: 8002
  root: /api

auth:
  jwt:
    key:
      algorithm: HS256
      publicKey: demo # change it in production environment and store it in a safe place
      symmetric: true
    options:
      expiresInSeconds: 14400

mongodb:
  connection_string: mongodb://demo:demo@localhost:27017/stroke-data

redis:
  host: localhost
  port: 6379
  select: 1 #use another db to store tokens
