version: '3.8'

services:
  gateway:
    image: it.unibo/gateway
    container_name: gateway
    ports:
      - "8001:8001"
    environment:
      VERTX_PROFILE: ${profile:-docker}
    depends_on:
      - redis
    restart: on-failure

  registry-service:
    image: it.unibo/registry-service
    container_name: registry-service
    environment:
      VERTX_PROFILE: ${profile:-docker}
    depends_on:
      - redis
    restart: on-failure

  auth-service:
    image: it.unibo/auth-service
    container_name: auth-service
    environment:
      VERTX_PROFILE: ${profile:-docker}
    depends_on:
      - redis
      - mongo
    restart: on-failure

  peer-service:
    image: it.unibo/peer-service
    container_name: peer-service
    environment:
      VERTX_PROFILE: ${profile:-docker}
    depends_on:
      - peerjs-server
      - mongo
    restart: on-failure

  session-service:
    image: it.unibo/session-service
    container_name: session-service
    environment:
      VERTX_PROFILE: ${profile:-docker}
    depends_on:
      - redis
      - mongo
    restart: on-failure

  record-service:
    image: it.unibo/record-service
    container_name: record-service
    environment:
      VERTX_PROFILE: ${profile:-docker}
    volumes:
      - ./recordings:/app/recordings
    restart: on-failure

  peerjs-server:
    image: it.unibo/peerjs-server
    container_name: peerjs-server
    ports:
      - "9000:9000"
    restart: on-failure

  frontend:
    image: it.unibo/frontend
    container_name: frontend
    depends_on:
      - gateway
    ports:
      - "8080:80"
    restart: on-failure

  redis:
    image: redis:5.0-alpine
    container_name: redis

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin # change in production env
      MONGO_INITDB_DATABASE: stroke-data
    volumes:
      - ./mongo-seed/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./data/mongodb:/data/db
      - ./data/mongodb_config:/data/configdb

  # use only the first time to import initial data to database
  mongo-seed:
    build:
      context: ./mongo-seed
    depends_on:
      - mongo