service:
  name: peer-service

discovery:
  backend:
    host: localhost
    port: 6379
    key: discovery-records

server:
  host: localhost
  port: 8005
  root: /api

mongodb:
  connection_string: mongodb://demo:demo@localhost:27017/stroke-data

peerjs:
  serverConfig:
    host: localhost
    port: 9000
    path: telestroke
    apiKey: demo # default key, change it in production env
    secure: false
  schedulingTime: 10000
