service:
  name: registry-service

discovery:
  backend:
    host: localhost
    port: 6379
    key: discovery-records

server:
  host: localhost
  port: 8003
  root: /api

healthCheck:
  schedulingTime: 30000
