service:
  name: session-service

discovery:
  backend:
    host: localhost
    port: 6379
    key: discovery-records

server:
  host: localhost
  port: 8004
  root: /api

mongodb:
  connection_string: mongodb://demo:demo@localhost:27017/stroke-data
